# escena(s) -> tema; GRAF/IA/CLIP se resuelven aparte
R = [
 (1, 3, 'pow_camp'), (4, 4, 'pow_check'), (5, 7, 'IA'), (8, 8, 'wss_troops'), (9, 9, 'field_hospital'), (10, 10, 'pow_camp'),
 (11, 11, 'IA'), (12, 12, 'pow_camp'), (13, 15, 'mengele'), (16, 18, 'berlin_1945'), (19, 19, 'nuremberg'),
 (20, 20, 'pow_camp'), (21, 21, 'degrelle'), (22, 22, 'baltic_legion'), (23, 23, 'veterans'), (24, 26, 'GRAF'),
 (27, 29, 'hitler_1933'), (30, 31, 'leibstandarte'), (32, 32, 'himmler'), (33, 34, 'ss_camps'), (35, 35, 'ss_camps'),
 (36, 38, 'wss_troops'), (39, 42, 'volunteers'), (43, 45, 'volunteers'), (46, 47, 'wss_troops'), (48, 51, 'le_paradis'),
 (52, 53, 'warsaw'), (54, 56, 'oradour'), (57, 60, 'ardennes'), (61, 64, 'malmedy'), (65, 69, 'wss_troops'),
 (70, 77, 'surrender_1945'), (78, 83, 'pow_camp'), (84, 88, 'charlemagne'), (89, 93, 'mengele'), (94, 96, 'archives'),
 (97, 112, 'nuremberg'), (113, 130, 'malmedy_trial'), (131, 140, 'kurt_meyer'), (141, 143, 'germany_1950s'),
 (144, 154, 'veterans'), (155, 156, 'adenauer'), (157, 162, 'bundeswehr'), (163, 169, 'veterans'), (170, 175, 'hausser'),
 (176, 187, 'oradour'), (188, 192, 'alsace'), (193, 198, 'oradour'), (199, 201, 'lammerding'), (202, 202, 'germany_1950s'),
 (203, 212, 'degrelle'), (213, 219, 'skorzeny'), (220, 228, 'ratlines'), (229, 232, 'mengele'),
 (233, 242, 'foreign_legion'), (243, 249, 'collab_trials'), (250, 255, 'charlemagne'), (256, 264, 'baltic_legion'),
 (265, 268, 'dp_camps'), (269, 272, 'galicia'), (273, 283, 'soviet_pows'), (284, 289, 'friedland'),
 (290, 297, 'peiper_late'), (298, 307, 'bitburg'), (308, 313, 'grass'), (314, 317, 'boere'), (318, 323, 'pensions'),
 (324, 326, 'riga'), (327, 333, 'ottawa'), (334, 335, 'GRAF'), (336, 342, 'recap'), (343, 346, 'veterans_old'),
 (347, 348, 'nuremberg'), (349, 353, 'GRAF'),
]
C, S = 'cat', 'search'
Q = {
 'pow_camp': [(C, 'Rheinwiesenlager'), (S, 'German prisoners of war 1945 camp'), (S, 'Kriegsgefangenenlager 1945 Bundesarchiv')],
 'pow_check': [(S, 'German prisoners searched American soldiers 1945'), (S, 'prisoners interrogation 1945 US Army')],
 'wss_troops': [(S, 'Bundesarchiv Waffen-SS Soldaten'), (S, 'Bundesarchiv Bild 101III Waffen-SS'), (S, 'Waffen-SS 1943 Bundesarchiv Panzer')],
 'field_hospital': [(S, 'Bundesarchiv Verwundete Sanitäter 1943'), (S, 'Bundesarchiv Lazarett Bluttransfusion')],
 'mengele': [(C, 'Josef Mengele'), (S, 'Auschwitz-Birkenau 1944 ramp'), (S, 'Josef Mengele Auschwitz')],
 'berlin_1945': [(S, 'Berlin 1945 ruins Reichstag'), (S, 'Bundesarchiv Berlin Zerstörung 1945')],
 'nuremberg': [(C, 'Nuremberg trials'), (S, 'International Military Tribunal Nuremberg courtroom'), (S, 'Nuremberg trial defendants dock')],
 'degrelle': [(C, 'Léon Degrelle'), (S, 'Légion Wallonie Degrelle'), (S, 'Playa de La Concha San Sebastián'), (S, 'Heinkel He 111 Bundesarchiv')],
 'baltic_legion': [(C, 'Latvian Legion'), (S, 'Latvian Legion 1944'), (S, 'Estonian Legion Waffen-SS')],
 'veterans': [(S, 'Bundesarchiv Soldatentreffen'), (S, 'HIAG Waffen-SS veterans'), (S, 'Bundesarchiv Kameradschaftstreffen'), (S, 'Waffen-SS Veteranen'), (S, 'Kriegsgräberstätte Gedenkfeier'), (S, 'Volkstrauertag 1955')],
 'hitler_1933': [(S, 'Bundesarchiv Hitler Reichskanzler 1933'), (S, 'Bundesarchiv Berlin 1933 Fackelzug')],
 'leibstandarte': [(C, '1st SS Panzer Division Leibstandarte SS Adolf Hitler'), (S, 'Leibstandarte Berlin 1935 Bundesarchiv'), (C, 'Sepp Dietrich')],
 'himmler': [(S, 'Bundesarchiv Heinrich Himmler 1938'), (S, 'Himmler inspecting SS')],
 'ss_camps': [(S, 'Dachau concentration camp 1933 Bundesarchiv'), (S, 'Buchenwald 1945 liberation'), (S, 'SS-Totenkopfverbände')],
 'volunteers': [(S, 'Bundesarchiv Legion Flandern'), (S, 'Bundesarchiv Freiwillige Waffen-SS Norwegen'), (S, 'Waffen-SS recruitment poster'), (S, 'Bundesarchiv Freiwilligen-Legion Niederlande')],
 'le_paradis': [(S, 'Le Paradis massacre memorial'), (S, 'Wormhoudt massacre memorial'), (S, 'Dunkirk 1940 British prisoners')],
 'warsaw': [(C, 'Warsaw Uprising'), (S, 'Warsaw Uprising 1944 ruins')],
 'oradour': [(C, 'Oradour-sur-Glane'), (S, 'Oradour-sur-Glane ruins'), (S, 'Oradour-sur-Glane village martyr'), (S, 'Oradour-sur-Glane voiture rouillée')],
 'ardennes': [(S, 'Battle of the Bulge 1944 Bundesarchiv'), (S, 'Kampfgruppe Peiper'), (S, 'Battle of the Bulge American soldiers snow')],
 'malmedy': [(C, 'Malmedy massacre'), (S, 'Baugnez Malmedy memorial'), (S, 'Malmedy massacre victims January 1945')],
 'surrender_1945': [(S, 'German soldiers surrender May 1945'), (S, 'German prisoners column 1945'), (S, 'Bundesarchiv Kapitulation 1945')],
 'charlemagne': [(S, 'Division Charlemagne Waffen-SS'), (S, 'Bad Reichenhall 1945'), (S, 'Leclerc 2e DB 1945'), (S, 'Légion des volontaires français')],
 'archives': [(S, 'archive files documents shelves'), (S, 'card index archive old')],
 'malmedy_trial': [(C, 'Malmedy massacre trial'), (S, 'Malmedy trial Dachau 1946'), (C, 'Joachim Peiper'), (S, 'Landsberg prison'), (S, 'Joseph McCarthy 1950')],
 'kurt_meyer': [(C, 'Kurt Meyer'), (S, 'Abbaye d\'Ardenne'), (S, 'Kurt Meyer trial Aurich'), (S, 'Dorchester Penitentiary')],
 'germany_1950s': [(S, 'Bundesarchiv Wiederaufbau 1950'), (S, 'Bundesarchiv Wirtschaftswunder'), (S, 'Bundesarchiv Düsseldorf 1955')],
 'adenauer': [(S, 'Bundesarchiv Konrad Adenauer 1953'), (S, 'Adenauer Rede 1952')],
 'bundeswehr': [(S, 'Bundesarchiv Bundeswehr 1956 Soldaten'), (S, 'Bundesarchiv Bundeswehr Vereidigung 1956'), (S, 'Bundeswehr 1955 Andernach'), (S, 'Bundeswehr 1957'), (S, 'Bundeswehr Rekruten 1956'), (S, 'Bundeswehr soldiers 1958')],
 'hausser': [(C, 'Paul Hausser'), (S, 'Paul Hausser Bundesarchiv'), (S, 'Hausser SS'), (S, 'Paul Hausser 1943')],
 'alsace': [(S, 'Malgré-nous Alsace'), (S, 'Strasbourg 1945'), (S, 'Bordeaux 1953')],
 'lammerding': [(S, 'Heinz Lammerding'), (S, 'Das Reich division 1944 Bundesarchiv'), (S, 'Tulle 1944')],
 'skorzeny': [(C, 'Otto Skorzeny'), (S, 'Gran Sasso Mussolini 1943 Bundesarchiv'), (S, 'Madrid 1960 Gran Vía')],
 'ratlines': [(S, 'Alois Hudal'), (S, 'Genoa port 1950'), (S, 'Buenos Aires 1950'), (S, 'Juan Perón 1950'), (S, 'Red Cross travel document 1949')],
 'foreign_legion': [(S, 'French Foreign Legion 1950s'), (S, 'Indochina War 1953'), (S, 'Dien Bien Phu 1954'), (S, 'Sidi Bel Abbès Légion étrangère')],
 'collab_trials': [(S, 'Nationaal Archief collaborateurs 1945'), (S, 'Quisling trial 1945'), (S, 'arrestatie NSB 1945')],
 'dp_camps': [(S, 'displaced persons camp 1946'), (S, 'Zedelgem prisoner camp'), (S, 'DP camp Latvian Germany')],
 'galicia': [(S, '14th Waffen Grenadier Division Galicia'), (S, 'Rimini 1946'), (S, 'Galicia Division 1943')],
 'soviet_pows': [(S, 'German prisoners of war Soviet Union'), (S, 'Bundesarchiv Kriegsgefangene Sowjetunion'), (S, 'Gulag camp')],
 'friedland': [(S, 'Bundesarchiv Friedland Heimkehrer 1955'), (S, 'Grenzdurchgangslager Friedland'), (S, 'Bundesarchiv Adenauer Moskau 1955')],
 'peiper_late': [(S, 'Traves Haute-Saône'), (S, 'Saône river village'), (S, 'house fire night')],
 'bitburg': [(S, 'Bitburg Kolmeshöhe'), (S, 'Reagan Kohl Bitburg 1985'), (S, 'Reagan Bergen-Belsen 1985'), (S, 'Elie Wiesel Reagan')],
 'grass': [(C, 'Günter Grass'), (S, 'Günter Grass 2006')],
 'boere': [(S, 'Aachen Landgericht'), (S, 'Eschweiler'), (S, 'Maastricht 1944')],
 'pensions': [(S, 'Bundestag Plenarsaal Bonn'), (S, 'Bundesversorgungsgesetz'), (S, 'old documents stamp')],
 'riga': [(S, 'Latvian Legion Remembrance Day Riga'), (S, '16 March Riga march'), (S, 'Freedom Monument Riga')],
 'ottawa': [(S, 'Zelensky Ottawa 2023'), (S, 'House of Commons Canada chamber'), (S, 'Parliament Hill Ottawa')],
 'recap': [(S, 'Bundesarchiv Joachim Peiper'), (S, 'Kurt Meyer Bundesarchiv'), (S, 'Degrelle 1944')],
 'veterans_old': [(S, 'old man portrait black and white'), (S, 'Bundesarchiv Rentner 1960'), (S, 'German village 1950s')],
}
