R = [
 (1, 3, 'reichskanzlei'), (4, 8, 'czech_1945'), (9, 9, 'silesia_1945'), (10, 13, 'hj_1945'), (14, 14, 'hitler_1945'), (16, 18, 'hj_general'), (19, 23, 'hj_general'),
 (25, 26, 'GRAF'), (27, 27, 'hitler_1933'), (28, 31, 'schirach'), (32, 38, 'norkus'), (39, 40, 'hj_general'),
 (43, 43, 'bdm'), (44, 47, 'hj_camps'), (48, 48, 'hj_general'), (51, 52, 'hj_general'), (53, 56, 'hj_general'),
 (57, 63, 'klv'), (64, 64, 'hj_general'), (66, 69, 'flakhelfer'), (70, 73, 'hj_division'), (74, 76, 'volkssturm'),
 (77, 80, 'white_rose'), (81, 87, 'edelweiss'), (88, 93, 'berlin_1945'), (94, 96, 'bunker'), (97, 99, 'axmann'),
 (100, 107, 'bormann'), (112, 117, 'pow_camp'), (118, 118, 'ruins_1945'), (119, 125, 'truemmerfrauen'),
 (126, 134, 'wolfskinder'), (135, 137, 'werwolf'), (138, 144, 'aachen'), (145, 155, 'gardelegen'),
 (156, 159, 'axmann'), (160, 174, 'nkvd_camps'), (175, 175, 'nuremberg'), (178, 184, 'nuremberg'), (186, 189, 'spandau'),
 (190, 196, 'ferdinand'), (197, 200, 'axmann'), (201, 202, 'hj_general'), (205, 205, 'nuremberg'), (210, 213, 'school_1945'),
 (214, 218, 'school_1945'), (219, 225, 'schulspeisung'), (226, 226, 'gya'), (227, 237, 'fdj'), (238, 238, 'school_1945'),
 (240, 251, 'skeptical'), (252, 260, 'bdm'), (261, 272, 'heck'), (273, 274, 'bonn_1950s'), (275, 284, 'ratzinger'),
 (285, 294, 'kohl'), (295, 305, 'writers'), (306, 310, 'edelweiss'), (311, 314, 'students_1968'), (317, 325, 'witnesses'),
 (326, 326, 'czech_1945'), (327, 327, 'pow_camp'), (328, 328, 'silesia_1945'), (329, 330, 'west_1960'), (331, 333, 'czech_1945'), (334, 335, 'GRAF'), (336, 341, 'recap'), (342, 347, 'hj_general'), (348, 353, 'GRAF'),
]
C, S = 'cat', 'search'
Q = {
 'czech_1945': [(S, 'Bundesarchiv Bild 183-V04744'), (S, 'Hitler Hitlerjugend März 1945 Reichskanzlei'), (S, 'Bundesarchiv Hitlerjunge Eisernes Kreuz 1945'), (S, 'Reichskanzlei Garten 1945'), (S, "Hitler's last public appearance"), (S, 'Hitler Youth Iron Cross 1945'), (S, 'Bundesarchiv Hitler Jungen Auszeichnung')],
 'reichskanzlei': [(S, 'Neue Reichskanzlei 1945'), (S, 'Reich Chancellery 1945 ruins'), (S, 'Reichskanzlei Garten'), (S, 'Bundesarchiv Reichskanzlei')],
 'silesia_1945': [(S, 'Schlesien 1945 Flüchtlinge'), (S, 'Bundesarchiv Treck Flüchtlinge 1945'), (S, 'Lauban 1945'), (S, 'Silesia 1945 refugees')],
 'hj_1945': [(S, 'Bundesarchiv Hitlerjunge 1945'), (S, 'Volkssturm Hitlerjugend 1945'), (S, 'Hitler Youth 1945 soldiers'), (S, 'Bundesarchiv Volkssturm Jungen')],
 'west_1960': [(S, 'Bundesarchiv Tischler 1960'), (S, 'Bundesarchiv Arbeiter 1964'), (S, 'Hückelhoven'), (S, 'Bundesarchiv Bauarbeiter 1960')],
 'hitler_1945': [(S, 'Bundesarchiv Hitler 1945'), (S, 'Hitler last photo 1945')],
 'hj_general': [(C, 'Hitler Youth'), (S, 'Bundesarchiv Hitlerjugend'), (S, 'Bundesarchiv Hitlerjungen'), (S, 'Bundesarchiv Jungvolk'), (S, 'Hitlerjugend Aufmarsch'), (S, 'Bundesarchiv Hitlerjugend Lager'), (S, 'Bundesarchiv Hitlerjugend 1936'), (S, 'Bundesarchiv Hitlerjugend 1939'), (S, 'Bundesarchiv Jungvolk 1934'), (S, 'Bundesarchiv Hitlerjungen Ausbildung')],
 'hitler_1933': [(S, 'Bundesarchiv Hitler Reichskanzler 1933 Januar'), (S, 'Bundesarchiv Fackelzug 1933')],
 'schirach': [(C, 'Baldur von Schirach'), (S, 'Bundesarchiv Baldur von Schirach'), (S, 'Reichsjugendführer Schirach')],
 'norkus': [(C, 'Herbert Norkus'), (S, 'Hitlerjunge Quex'), (S, 'Herbert Norkus Grab')],
 'bdm': [(C, 'Bund Deutscher Mädel'), (S, 'Bundesarchiv BDM'), (S, 'Bundesarchiv Jungmädel'), (S, 'Melita Maschmann')],
 'hj_camps': [(S, 'Bundesarchiv Hitlerjugend Zeltlager'), (S, 'Bundesarchiv Hitlerjugend Fahrt'), (S, 'Bundesarchiv Hitlerjugend Sport'), (S, 'Bundesarchiv Wehrertüchtigungslager'), (S, 'Bundesarchiv Hitlerjugend Geländesport'), (S, 'Bundesarchiv Hitlerjugend Schießausbildung')],
 'klv': [(C, 'Kinderlandverschickung'), (S, 'Kinderlandverschickung Bundesarchiv'), (S, 'KLV-Lager')],
 'flakhelfer': [(C, 'Luftwaffenhelfer'), (S, 'Bundesarchiv Luftwaffenhelfer'), (S, 'Flakhelfer 1944'), (S, 'Bundesarchiv Flak Geschütz 1944')],
 'hj_division': [(C, '12th SS Panzer Division Hitlerjugend'), (S, 'Bundesarchiv Hitlerjugend Division Normandie 1944')],
 'volkssturm': [(C, 'Volkssturm'), (S, 'Bundesarchiv Volkssturm'), (S, 'Volkssturm Panzerfaust Hitlerjunge')],
 'white_rose': [(C, 'White Rose'), (S, 'Hans und Sophie Scholl'), (S, 'Geschwister-Scholl-Platz'), (S, 'Sophie Scholl'), (S, 'Weiße Rose Flugblatt'), (S, 'Lichthof Universität München')],
 'edelweiss': [(C, 'Edelweißpiraten'), (S, 'Edelweißpiraten Köln Ehrenfeld'), (S, 'Bartholomäus Schink'), (S, 'EL-DE-Haus Köln'), (S, 'Gestapo Köln 1944')],
 'berlin_1945': [(S, 'Berlin 1945 Havel Brücke Pichelsdorf'), (S, 'Bundesarchiv Berlin April 1945'), (S, 'Battle of Berlin 1945 ruins'), (S, 'Berlin 1945 Panzerfaust')],
 'bunker': [(C, 'Führerbunker'), (S, 'Führerbunker 1947')],
 'axmann': [(C, 'Artur Axmann'), (S, 'Artur Axmann Bundesarchiv'), (S, 'Lübeck 1945')],
 'bormann': [(C, 'Martin Bormann'), (S, 'Lehrter Bahnhof'), (S, 'Bormann skull 1972')],
 'pow_camp': [(C, 'Rheinwiesenlager'), (S, 'German boy soldiers captured 1945'), (S, 'German prisoners of war 1945 boys'), (S, 'Remagen prisoner camp 1945')],
 'ruins_1945': [(S, 'Bundesarchiv Trümmer 1945'), (S, 'Berlin ruins 1945 children'), (S, 'Dresden 1945 ruins')],
 'truemmerfrauen': [(C, 'Trümmerfrauen'), (S, 'Bundesarchiv Trümmerfrauen'), (S, 'Trümmerfrau Berlin 1945')],
 'wolfskinder': [(S, 'Wolfskinder Ostpreußen'), (S, 'East Prussia refugees 1945'), (S, 'Bundesarchiv Flüchtlinge Ostpreußen 1945'), (S, 'Wolfskinder Litauen')],
 'werwolf': [(S, 'Werwolf 1945 Nazi'), (S, 'Radio Werwolf'), (S, 'Bundesarchiv Werwolf')],
 'aachen': [(S, 'Aachen 1944 ruins'), (S, 'Franz Oppenhoff'), (S, 'Aachen October 1944 US Army')],
 'gardelegen': [(C, 'Gardelegen massacre'), (S, 'Gardelegen barn 1945'), (S, 'Isenschnibbe')],
 'nkvd_camps': [(C, 'NKVD special camp Nr. 7'), (S, 'Speziallager Ketschendorf'), (S, 'sowjetisches Speziallager'), (S, 'Speziallager Buchenwald'), (S, 'Waldfriedhof Halbe')],
 'nuremberg': [(C, 'Nuremberg trials'), (S, 'Nuremberg trial Schirach'), (S, 'Nuremberg trials defendants')],
 'spandau': [(C, 'Spandau Prison'), (S, 'Spandau Prison 1966'), (S, 'Kröv Mosel')],
 'ferdinand': [(C, 'Ferdinand von Schirach'), (S, 'Ferdinand von Schirach Lesung')],
 'school_1945': [(S, 'Bundesarchiv Schule 1945'), (S, 'Bundesarchiv Schulklasse 1946'), (S, 'school Germany 1946 children'), (S, 'Bundesarchiv Schulbeginn 1945')],
 'schulspeisung': [(C, 'Schulspeisung'), (S, 'Hoover-Speisung'), (S, 'Schulspeisung 1947'), (S, 'CARE Paket 1947'), (S, 'Bundesarchiv Kinderspeisung'), (S, 'Quäkerspeisung'), (S, 'Bundesarchiv Schulspeisung'), (S, 'Bundesarchiv Kinder Essen 1946'), (S, 'Bundesarchiv Hunger 1947'), (S, 'CARE package Germany')],
 'gya': [(S, 'German Youth Activities US Army 1947'), (S, 'Bundesarchiv Jugendheim 1948'), (S, 'Berlin children 1948 American soldiers'), (S, 'German Youth Activities'), (S, 'Bundesarchiv Jugendclub 1947'), (S, 'Bundesarchiv amerikanische Soldaten Kinder'), (S, 'Bundesarchiv Jugend 1947')],
 'fdj': [(C, 'Freie Deutsche Jugend'), (S, 'Bundesarchiv FDJ 1946'), (S, 'Bundesarchiv FDJ 1949 Pfingsttreffen'), (S, 'Erich Honecker FDJ')],
 'skeptical': [(S, 'Bundesarchiv Jugendliche 1950'), (S, 'Bundesarchiv Lehrling 1950'), (S, 'Bundesarchiv Jugend 1955'), (S, 'Helmut Schelsky')],
 'heck': [(S, 'Bundesarchiv Segelflug Hitlerjugend'), (S, 'Flieger-Hitlerjugend'), (S, 'Bundesarchiv Segelflugzeug 1938'), (S, 'Wasserkuppe Segelflug 1937'), (S, 'Wittlich 1945')],
 'bonn_1950s': [(S, 'Bundesarchiv Wiederaufbau 1950'), (S, 'Bundesarchiv Bonn 1955')],
 'ratzinger': [(C, 'Joseph Ratzinger in the 1950s'), (S, 'Joseph Ratzinger 1951'), (S, 'Benedict XVI Auschwitz 2006'), (S, 'Traunstein'), (S, 'Benedict XVI 2005'), (S, 'Benedikt XVI Wahl 2005'), (S, 'Pope Benedict XVI election balcony'), (S, 'Joseph Ratzinger 1977')],
 'kohl': [(S, 'Bundesarchiv Helmut Kohl 1984'), (S, 'Helmut Kohl Israel 1984'), (S, 'Helmut Kohl 1960'), (S, 'Ludwigshafen 1945'), (C, 'Helmut Kohl'), (S, 'Bundesarchiv B 145 Helmut Kohl'), (S, 'Helmut Kohl 1982'), (S, 'Knesset 1984')],
 'writers': [(C, 'Günter Grass'), (C, 'Martin Walser'), (C, 'Siegfried Lenz'), (C, 'Dieter Hildebrandt'), (S, 'NSDAP Mitgliedskarte'), (S, 'Martin Walser 1960'), (S, 'Siegfried Lenz 1960'), (S, 'Dieter Hildebrandt 1965'), (S, 'Günter Grass 1961')],
 'students_1968': [(S, 'Bundesarchiv Studentenbewegung 1968'), (S, 'Berlin 1968 Demonstration Studenten'), (S, 'Bundesarchiv Studenten 1967'), (S, 'Rudi Dutschke'), (S, 'Vietnamkongress 1968'), (S, 'Studentenbewegung 1968'), (S, 'Benno Ohnesorg')],
 'witnesses': [(S, 'Zeitzeuge Schule'), (S, 'Zeitzeugengespräch'), (S, 'old man portrait black and white')],
 'recap': [(S, 'Bundesarchiv Baldur von Schirach 1936'), (S, 'Artur Axmann 1943'), (S, 'Bundesarchiv Hitlerjugend 1943')],
}
