# Biblioteca de recursos visuales: clave -> (tipo, clip, qué buscar, dónde, prompt G-Labs en inglés, luz)
# tipo: NARA, BA, COM, STK, MAPA, GRAF, GLABS
C = 'commons.wikimedia.org'
NARA = 'catalog.archives.gov / archive.org (solo colecciones del gobierno de EE. UU.)'
BAW = 'commons.wikimedia.org → buscar "Bundesarchiv" + el término'
STKV = 'pexels.com/videos / pixabay.com/videos'
STKF = 'pexels.com / pixabay.com / unsplash.com'
MAPW = 'mapa propio con base de Natural Earth (naturalearthdata.com) u OpenStreetMap'
GRW = 'hecho en el editor (texto y gráficos propios, sin IA)'
GL = 'G-Labs (no hay material libre de esta escena)'

A = {
# ---------- HARZ / BAD SACHSA ----------
'harz_valley': ('STK', 1, 'buscar: "Harz forest valley fog" / "misty pine forest valley"', STKV,
  'Wide aerial shot of a misty pine forest valley in the Harz mountains of central Germany, low clouds clinging to dark fir trees, a narrow gravel road winding down to a few wooden houses', 'past'),
'borntal_arrival': ('GLABS', 0, 'recreación: cuatro niños llegan al hogar del Borntal', GL,
  'Cinematic wide shot from behind of four German children of different ages, the oldest a ten-year-old boy, holding small battered leather suitcases, standing before a group of wooden Black Forest style chalets in a forest clearing, August 1944, a stern woman in a gray 1940s dress waiting at the door', 'past'),
'borntal_houses': ('COM', 0, 'casas del antiguo hogar infantil del Borntal en Bad Sachsa — "Bad Sachsa Borntal" / "Kinderheim Borntal"', C + ' → Category:Bad Sachsa',
  'Establishing shot of several dark wooden chalet-style children\'s holiday houses with steep roofs and carved balconies in a narrow forested valley near Bad Sachsa, Harz, 1944, empty swings in the yard', 'past'),
'ledger_cross': ('STK', 1, 'buscar: "old ledger handwriting" / "vintage register ink pen"', STKV,
  'Extreme close-up of an old 1940s registry ledger, a fountain pen striking through a handwritten surname with a heavy ink line, only illegible scribbles visible', 'prison'),
'suitcase_child': ('STK', 1, 'buscar: "vintage suitcase" / "old leather suitcase luggage tag"', STKV,
  'Close-up of a small worn child\'s leather suitcase on a wooden dormitory floor with a blank paper luggage tag tied to the handle, 1944', 'past'),
'bad_sachsa_town': ('COM', 0, 'vista de Bad Sachsa (postales antiguas o fotos actuales)', C + ' → Category:Bad Sachsa',
  'Wide shot of the small spa town of Bad Sachsa nestled among forested Harz hills, half-timbered houses and a church steeple, 1944', 'past'),
'blackforest_house': ('STK', 0, 'buscar: "Black Forest farmhouse" / "Schwarzwaldhaus"', STKF,
  'Medium shot of a traditional dark wooden Black Forest style house with a huge sloping roof and flower boxes, picture-postcard setting, cold light', 'past'),
'dormitory': ('GLABS', 0, 'recreación: dormitorio del hogar', GL,
  'Interior of a wooden dormitory in a 1944 German children\'s home, two rows of narrow iron beds with gray wool blankets perfectly made, a single bare bulb, a small window showing pine trees', 'prison'),
'kids_group_back': ('GLABS', 0, 'recreación: grupo de niños de espaldas', GL,
  'Wide shot from behind of a group of about twenty German children aged two to fifteen in 1940s clothes lined up in rows in a forest clearing between wooden chalets, a female supervisor watching', 'prison'),
'kids_shoes': ('STK', 1, 'buscar: "row of children shoes" / "old children shoes"', STKV,
  'Row of small worn 1940s children\'s leather shoes of different sizes lined up against a wooden wall, from tiny baby shoes to a teenager\'s boots', 'prison'),
'kids_separated': ('GLABS', 0, 'recreación: separan a los niños por edad', GL,
  'Medium shot of a stern female caretaker in a gray 1940s dress leading a line of young girls one way while a line of boys walks the other way across a wooden veranda, a little girl looking back over her shoulder', 'prison'),
'name_list': ('GLABS', 0, 'recreación: lista de nombres falsos', GL,
  'Extreme close-up of a woman\'s hand writing new names on a typed list in a 1944 office, only illegible handwriting visible, a rubber stamp beside it', 'prison'),
'archive_boxes': ('STK', 1, 'buscar: "archive files boxes" / "old documents archive"', STKV,
  'Rows of old cardboard archive boxes and yellowed file folders on metal shelves in a dim archive', 'prison'),
'adoption_family': ('GLABS', 0, 'recreación: familia leal al régimen (sin símbolos)', GL,
  'Faded 1940s studio portrait style image of a stiff German couple in formal clothes posing in a bourgeois living room, an empty chair beside them, a small boy\'s coat hanging on it, unsettling mood', 'prison'),
'boy_window': ('GLABS', 0, 'recreación: niño mirando por la ventana', GL,
  'Close-up of a ten-year-old German boy with short light-brown hair parted to the side, wearing a knitted 1940s sweater, staring out of a rain-streaked window of a wooden house at the dark forest', 'prison'),
'diary': ('STK', 1, 'buscar: "old diary writing pencil" / "vintage notebook handwriting"', STKV,
  'Close-up of a twelve-year-old girl\'s hand writing with a pencil in a small worn diary by candlelight, illegible handwriting', 'prison'),
'kids_bed_night': ('GLABS', 0, 'recreación: niños despiertos de noche', GL,
  'Night scene in a wooden dormitory, moonlight through a small window, a little girl with light-brown bobbed hair sitting up awake in an iron bed hugging her knees, other children asleep', 'prison'),
'autumn_forest': ('STK', 1, 'buscar: "autumn forest leaves falling"', STKV,
  'Autumn leaves falling in a German forest beside a wooden fence, October 1944', 'past'),
'mother_hug_gate': ('GLABS', 0, 'recreación: una madre recoge a su hijo', GL,
  'Medium shot of a German mother in a 1940s coat kneeling to hug her small son at the gate of a wooden children\'s home, other children watching from the veranda', 'past'),
'spring_forest': ('STK', 1, 'buscar: "spring snow melting forest" / "melting snow stream"', STKV,
  'Melting snow and a small stream in a pine forest in early spring, gray sky, 1945', 'end'),
'truck_kids': ('GLABS', 0, 'recreación: camión de la Wehrmacht con niños', GL,
  'A 1940s German Opel Blitz army truck with a canvas cover driving down a forest road, small children\'s faces visible in the back, gray spring light, April 1945', 'end'),
'kids_window_us': ('GLABS', 0, 'recreación: niños ven llegar a los estadounidenses', GL,
  'Over-the-shoulder shot of four children at the window of a wooden house watching an American army jeep with white star markings drive into the valley, April 1945', 'end'),
# ---------- PERSONAJES REALES (archivo) ----------
'claus_portrait': ('COM', 0, 'retratos de Claus von Stauffenberg (años 30, antes de la herida)', C + ' → Category:Claus von Stauffenberg',
  'Dramatic portrait of a tall slim German aristocratic officer in his early thirties with dark wavy hair combed back, a strong straight nose and dark eyes, in a plain field-gray uniform without insignia, 1930s', 'past'),
'claus_patch': ('COM', 0, 'foto de Stauffenberg con el parche en el ojo (1943-1944)', C + ' → Category:Claus von Stauffenberg',
  'Dramatic portrait of a German officer in his mid-thirties with dark wavy hair, a black eye patch over his left eye and an empty right sleeve folded at the wrist, plain field-gray uniform without insignia, 1944', 'past'),
'claus_hitler_15jul': ('BA', 0, 'Bundesarchiv: Stauffenberg en la Guarida del Lobo junto a Hitler y Keitel, 15 de julio de 1944 ("Führerhauptquartier Stauffenberg Hitler Keitel")', BAW,
  'Archival style photo of a group of German officers in field-gray uniforms without insignia standing outside a wooden hut in a forest compound in July 1944, one tall officer with an eye patch standing slightly apart', 'past'),
'himmler_portrait': ('BA', 0, 'Bundesarchiv: retrato de Heinrich Himmler', BAW + ' / Category:Heinrich Himmler',
  'Portrait of a German official in his forties with round rimless glasses, a small mustache and a weak chin, in a dark uniform without insignia, cold expression', 'prison'),
'himmler_speech': ('BA', 0, 'Bundesarchiv: Himmler hablando en un atril / tribuna', BAW + ' / Category:Heinrich Himmler',
  'A German official with round rimless glasses speaking at a lectern in a wood-paneled hall to rows of uniformed party officials seen from behind, no insignia, 1944', 'prison'),
'hitler_1933': ('BA', 0, 'Bundesarchiv: Hitler nombrado canciller, 30 de enero de 1933', BAW,
  'Archival style photo of a crowd with torches in front of a government building in Berlin at night, January 1933, no flags or symbols visible', 'past'),
'hitler_radio': ('BA', 0, 'Bundesarchiv: Hitler hablando ante un micrófono de radio', BAW,
  'Close-up of an old 1940s radio microphone in a dark studio, a red on-air lamp glowing', 'night'),
'hitler_mussolini': ('BA', 0, 'Bundesarchiv: Hitler y Mussolini en la Guarida del Lobo el 20 de julio de 1944 (sala destruida)', BAW + ' / Category:20 July plot',
  'Archival style photo of a wrecked wooden briefing room in a forest headquarters, shattered windows, splintered map table, officers inspecting the damage, July 1944', 'past'),
'olbricht': ('BA', 0, 'Bundesarchiv: retrato del general Friedrich Olbricht', BAW + ' / Category:Friedrich Olbricht',
  'Portrait of a German general in his fifties with round glasses and thinning hair, plain uniform without insignia, 1943', 'past'),
'fromm': ('BA', 0, 'Bundesarchiv: retrato del general Friedrich Fromm', BAW + ' / Category:Friedrich Fromm',
  'Portrait of a heavyset German general in his fifties with a stern face, plain uniform without insignia, 1944', 'past'),
'conspirators_bendler': ('COM', 0, 'retratos de Olbricht, Mertz von Quirnheim y Werner von Haeften', C + ' → Category:20 July plot',
  'Three archival style portraits side by side of German officers in plain uniforms without insignia, faded paper, 1944', 'night'),
'berthold_brother': ('BA', 0, 'Bundesarchiv: Berthold von Stauffenberg ante el Tribunal del Pueblo, agosto de 1944', BAW + ' / Category:Volksgerichtshof',
  'Archival style photo of a gaunt German man in his late thirties in a crumpled civilian suit standing before a courtroom bench draped in dark cloth, August 1944', 'prison'),
'uexkull': ('BA', 0, 'Bundesarchiv: Nikolaus von Üxküll ante el Tribunal del Pueblo', BAW + ' / Category:Volksgerichtshof',
  'Archival style photo of an elderly German man with white hair in a civilian suit standing before a courtroom bench, 1944', 'prison'),
'yorck': ('BA', 0, 'Bundesarchiv: Peter Yorck von Wartenburg ante el Tribunal del Pueblo', BAW + ' / Category:Peter Yorck von Wartenburg',
  'Archival style photo of a thin German man in his forties in a civilian suit standing very straight before a courtroom bench, 1944', 'prison'),
'hofacker': ('BA', 0, 'Bundesarchiv: Caesar von Hofacker ante el Tribunal del Pueblo', BAW + ' / Category:Caesar von Hofacker',
  'Archival style photo of a German man in his forties with short hair in a civilian suit before a courtroom bench, 1944', 'prison'),
'remer': ('BA', 0, 'Bundesarchiv: retrato de Otto Ernst Remer (1944)', BAW + ' / Category:Otto Ernst Remer',
  'Portrait of a young German major in his early thirties with a hard face, plain uniform without insignia, 1944', 'post'),
'kaltenbrunner': ('NARA', 0, 'Ernst Kaltenbrunner en los juicios de Núremberg (fotos del ejército de EE. UU.)', NARA + ' / ' + C + ' → Category:Ernst Kaltenbrunner',
  'Portrait of a very tall German official in his forties with a long scarred face and dark hair, gray civilian suit, 1945', 'end'),
'schuschnigg': ('COM', 0, 'retrato de Kurt Schuschnigg', C + ' → Category:Kurt Schuschnigg',
  'Portrait of an Austrian statesman in his forties with round glasses and slicked-back hair, dark suit, 1930s', 'end'),
'blum_niemoller': ('COM', 0, 'retratos de Léon Blum (Gallica/Agence Meurisse, dominio público) y Martin Niemöller (Bundesarchiv)', C + ' → Category:Léon Blum / Category:Martin Niemöller',
  'Two archival style portraits side by side: an elderly French statesman with a mustache and round glasses, and a German Protestant pastor in his fifties in a dark clerical coat', 'end'),
'fritz_bauer': ('COM', 0, 'retrato de Fritz Bauer', C + ' → Category:Fritz Bauer',
  'Portrait of a German prosecutor in his late forties with thick wavy gray hair, heavy eyebrows and dark-rimmed glasses, dark suit, 1950s', 'post'),
'eichmann_trial': ('COM', 0, 'juicio a Eichmann en Jerusalén (fotos de la Oficina de Prensa del Gobierno de Israel, dominio público)', C + ' → Category:Trial of Adolf Eichmann',
  'Wide shot of a 1961 courtroom with a glass booth at one side, judges at a high bench, rows of journalists', 'post'),
'auschwitz_trial': ('COM', 0, 'juicio de Auschwitz en Fráncfort (1963-1965)', C + ' → Category:Frankfurt Auschwitz trials',
  'Wide shot of a crowded 1960s German courtroom with rows of defendants in suits, judges in black robes, press photographers', 'post'),
'berthold_old': ('COM', 0, 'Berthold Maria von Stauffenberg (fotos recientes con licencia libre)', C + ' → Category:Berthold Maria Schenk Graf von Stauffenberg',
  'Portrait of a dignified German man in his eighties with white hair and a calm face, dark jacket, modern day, soft daylight', 'post'),
'melitta': ('COM', 0, 'retrato de Melitta Schenk Gräfin von Stauffenberg (si hay uno con licencia libre)', C + ' → Category:Melitta Schenk Gräfin von Stauffenberg',
  'Portrait of a German woman in her early forties with short dark hair and a determined face, wearing a 1940s leather flying jacket, an airfield behind her', 'past'),
'alexander': ('COM', 0, 'retrato de Alexander von Stauffenberg (si hay uno con licencia libre)', C + ' → Category:Alexander Schenk Graf von Stauffenberg',
  'Portrait of a tall German man in his late thirties with dark hair and a long thoughtful face, wearing a worn soldier\'s overcoat without insignia, 1944', 'past'),
'wuerttemberg_king': ('COM', 0, 'retrato del rey Guillermo II de Wurtemberg (dominio público)', C + ' → Category:William II of Württemberg',
  'Archival style portrait of an elderly German king with a white beard in a dark uniform, early 1900s', 'past'),
'brothers_young': ('COM', 0, 'los hermanos Stauffenberg de jóvenes (solo si la foto tiene licencia libre)', C + ' → Category:Stauffenberg family',
  'Faded 1920s photograph of three German teenage brothers in dark suits, two of them twins, standing on the steps of a stone manor house', 'past'),
# ---------- LUGARES (archivo y actuales) ----------
'bamberg_town': ('STK', 1, 'buscar: "Bamberg old town" / "Bamberg aerial"', STKV,
  'Aerial view of the old town of Bamberg, Bavaria, red tiled roofs, baroque church towers and the river Regnitz', 'past'),
'bamberg_old': ('COM', 0, 'postales antiguas de Bamberg (años 1900-1930, dominio público)', C + ' → Category:Bamberg in the 1930s / Category:Old postcards of Bamberg',
  'Faded 1930s postcard style view of Bamberg old town with the cathedral towers, horse carts on a cobbled street', 'past'),
'kaunas_old': ('COM', 0, 'Kaunas hacia 1910 (postales y fotos de dominio público)', C + ' → Category:Kaunas in the 1910s',
  'Faded 1910s photograph of a street in Kaunas, Lithuania, under the Russian Empire, horse-drawn carriages, an orthodox church dome', 'past'),
'jettingen': ('COM', 0, 'castillo de Jettingen (lugar de nacimiento de Claus)', C + ' → Category:Schloss Jettingen',
  'Wide shot of a white Swabian castle with a red roof in the village of Jettingen, Bavarian Swabia', 'past'),
'altes_schloss': ('COM', 0, 'Altes Schloss de Stuttgart, donde creció Claus', C + ' → Category:Altes Schloss (Stuttgart)',
  'Wide shot of the Old Castle of Stuttgart, a Renaissance palace with round towers and an arcaded courtyard', 'past'),
'lautlingen': ('COM', 0, 'castillo de Lautlingen (Albstadt), casa de los Stauffenberg', C + ' → Category:Schloss Lautlingen',
  'Wide shot of a modest white manor house with a steep roof and a small tower in the village of Lautlingen, Swabian Jura, surrounded by green hills, summer', 'past'),
'swabian_jura': ('STK', 1, 'buscar: "Swabian Alb" / "Schwäbische Alb landscape"', STKV,
  'Rolling green hills and juniper heath of the Swabian Jura in summer, a small village with a church in the valley', 'past'),
'wolfsschanze_ruins': ('COM', 1, 'ruinas actuales de la Guarida del Lobo (Gierłoż, Polonia)', C + ' → Category:Wolf\'s Lair (también hay clips en pexels/pixabay: "Wolf\'s Lair")',
  'Massive cracked concrete bunker ruins overgrown with moss and trees in a dark forest in former East Prussia', 'past'),
'wolfsschanze_room': ('BA', 0, 'Bundesarchiv: la barraca de reuniones destruida tras el atentado del 20 de julio de 1944', BAW + ' / Category:20 July plot',
  'Archival style photo of a destroyed wooden briefing hut, collapsed ceiling boards, shattered heavy oak map table, scattered papers, July 1944', 'past'),
'bendlerblock': ('COM', 0, 'edificio del Bendlerblock (calle Stauffenberg, Berlín)', C + ' → Category:Bendlerblock',
  'Wide shot of a large gray stone government building in Berlin with tall windows, the Bendlerblock, overcast sky', 'night'),
'bendler_memorial': ('COM', 0, 'patio de honor del Bendlerblock: estatua y placa del memorial', C + ' → Category:Gedenkstätte Deutscher Widerstand',
  'Bronze statue of a young man with bound hands in a quiet stone courtyard with a memorial plaque and fresh wreaths, Berlin', 'post'),
'ploetzensee': ('COM', 0, 'memorial de Plötzensee (sala de ejecuciones)', C + ' → Category:Gedenkstätte Plötzensee',
  'Interior of a bare brick execution shed with a steel beam under the ceiling, two windows, a single memorial wreath on the floor, Berlin', 'prison'),
'matthaus_cemetery': ('COM', 0, 'cementerio Alter St.-Matthäus-Kirchhof (Schöneberg)', C + ' → Category:Alter St.-Matthäus-Kirchhof',
  'Old Berlin cemetery at dawn, weathered gravestones and ivy, a freshly dug patch of earth', 'night'),
'foggy_field': ('STK', 1, 'buscar: "foggy field morning" / "empty field fog"', STKV,
  'Flat empty fields outside Berlin under morning fog, wind blowing over the ground', 'night'),
'volksempfanger': ('COM', 0, 'radio Volksempfänger (foto del objeto)', C + ' → Category:Volksempfänger',
  'Close-up of a 1930s German Bakelite people\'s radio receiver glowing on a kitchen shelf at night', 'night'),
'posen_castle': ('COM', 0, 'castillo imperial de Posen (Poznań)', C + ' → Category:Imperial Castle in Poznań',
  'Wide shot of a massive neo-Romanesque imperial castle in Poznan under a gray sky, 1944', 'prison'),
'gauleiters': ('BA', 0, 'Bundesarchiv: reunión de gauleiters / jerarcas del partido (sin primeros planos de símbolos)', BAW,
  'Rows of German party officials in brown uniforms without insignia seated in a dim conference hall, seen from behind', 'prison'),
'sachsenspiegel': ('COM', 0, 'miniaturas medievales del Sachsenspiegel (dominio público)', C + ' → Category:Sachsenspiegel',
  'Medieval illuminated manuscript page with small painted figures of judges and accused men', 'prison'),
'germanic_painting': ('COM', 0, 'pinturas del siglo XIX sobre los antiguos germanos (dominio público)', C + ' → Category:Germanic peoples in art',
  '19th-century romantic oil painting style scene of an ancient Germanic tribal assembly in a forest clearing', 'prison'),
'nuremberg_chart': ('COM', 0, 'tabla de las leyes raciales de Núremberg de 1935', C + ' → Category:Nuremberg Laws',
  'Old yellowed 1935 genealogical chart with rows of black, white and half-shaded circles, no readable text', 'prison'),
'rottweil': ('COM', 0, 'casco antiguo de Rottweil', C + ' → Category:Rottweil',
  'Old town of Rottweil, a medieval tower and stone buildings at dusk', 'prison'),
'gestapo_hq': ('BA', 0, 'Bundesarchiv: sede de la Gestapo en la calle Prinz Albrecht 8', BAW + ' / Category:Prinz-Albrecht-Straße 8',
  'Archival style photo of a massive gray neoclassical building on a Berlin street in the 1930s, black cars parked outside', 'prison'),
'topographie': ('COM', 0, 'restos de las celdas de la Gestapo (Topografía del Terror)', C + ' → Category:Topographie des Terrors',
  'Excavated brick cellar walls of old prison cells under a gray Berlin sky', 'prison'),
'alexanderplatz': ('BA', 0, 'Bundesarchiv: jefatura de policía de Alexanderplatz (años 30)', BAW + ' / Category:Polizeipräsidium Berlin',
  'Archival style photo of a huge red-brick police headquarters building on Alexanderplatz in Berlin, 1930s', 'prison'),
'ravensbrueck': ('COM', 0, 'memorial de Ravensbrück (muro, lago, edificios)', C + ' → Category:Ravensbrück concentration camp',
  'Long gray camp wall with barbed wire beside a cold lake under a winter sky, Ravensbrück', 'prison'),
'ravensbrueck_bunker': ('COM', 0, 'edificio de celdas (Zellenbau) de Ravensbrück', C + ' → Category:Ravensbrück concentration camp',
  'Long two-story brick cell block with small barred windows, Ravensbrück, winter', 'prison'),
'frankfurt_oder': ('COM', 0, 'Fráncfort del Óder antes de 1945 (postales) o el río Óder', C + ' → Category:Frankfurt (Oder) / Category:Oder',
  'Old town of Frankfurt an der Oder in winter, brick Gothic church and the frozen river Oder, January 1945', 'prison'),
'auschwitz_gate': ('COM', 0, 'puerta de Auschwitz (foto actual, encuadre respetuoso)', C + ' → Category:Auschwitz concentration camp',
  'Snow-covered railway tracks leading to a brick gatehouse under a gray winter sky', 'prison'),
'lazarettzug': ('BA', 0, 'Bundesarchiv: tren hospital (Lazarettzug)', BAW,
  'Interior of a 1940s hospital train carriage with stacked stretcher beds, dim light, a nurse walking between them', 'prison'),
'st_josef': ('COM', 0, 'hospital San José de Potsdam (St. Josefs-Krankenhaus)', C + ' → Category:St. Josefs-Krankenhaus Potsdam',
  'Exterior of an old red-brick Catholic hospital in Potsdam with a small chapel tower, winter 1945', 'prison'),
'schoenberg': ('COM', 0, 'Schönberg (Baja Baviera, Bosque Bávaro)', C + ' → Category:Schönberg (Niederbayern)',
  'Small Bavarian Forest village with a church and a school building among dark forested hills, April 1945', 'end'),
'trogen': ('COM', 0, 'Trogen (Alta Franconia, cerca de Hof)', C + ' → Category:Trogen (Oberfranken)',
  'Small Upper Franconian village with a church and farmhouses near Hof, spring 1945', 'end'),
'buchenwald': ('COM', 0, 'puerta y memorial de Buchenwald', C + ' → Category:Buchenwald concentration camp',
  'Iron gate and gatehouse of a concentration camp on a hill under heavy clouds, Buchenwald', 'end'),
'buchenwald_1945': ('NARA', 0, 'Buchenwald, abril de 1945 (Signal Corps): solo barracones y vistas generales, SIN cuerpos', NARA + ' → "Buchenwald April 1945"',
  'Archival style photo of long wooden barracks behind barbed wire on a hillside, April 1945', 'end'),
'dachau': ('COM', 0, 'memorial de Dachau (puerta, explanada)', C + ' → Category:Dachau concentration camp',
  'Wide empty gravel roll-call square and barracks foundations of Dachau memorial under a gray sky', 'end'),
'nordhausen_ruins': ('NARA', 0, 'Nordhausen destruida, abril de 1945: solo vistas de la ciudad, SIN cuerpos', NARA + ' → "Nordhausen 1945"',
  'Archival style photo of a bombed German town in April 1945, a destroyed railway station with twisted tracks and collapsed roofs', 'end'),
'niederdorf': ('COM', 0, 'Niederdorf / Villabassa (Tirol del Sur)', C + ' → Category:Villabassa',
  'Alpine village of Niederdorf in South Tyrol, church tower and the Dolomites behind, spring', 'end'),
'braies_hotel': ('STK', 1, 'buscar: "Lago di Braies" / "Pragser Wildsee" (y el hotel en ' + C + ' → Category:Hotel Pragser Wildsee)', STKV,
  'A large old grand hotel on the shore of an emerald alpine lake surrounded by Dolomite peaks, Lago di Braies', 'end'),
'dolomites': ('STK', 1, 'buscar: "Dolomites mountains clouds"', STKV,
  'Jagged Dolomite peaks emerging from clouds at dawn', 'end'),
'capri': ('STK', 1, 'buscar: "Capri island aerial"', STKV,
  'Aerial view of the island of Capri, rocky cliffs and blue sea', 'post'),
'kirchlauter': ('COM', 0, 'Kirchlauter (castillo y pueblo)', C + ' → Category:Kirchlauter',
  'Small Franconian village with a moated castle near Bamberg, autumn light', 'post'),
'nina_grave': ('COM', 0, 'tumba de Nina en Kirchlauter (si hay foto libre)', C + ' → Category:Kirchlauter',
  'A simple stone grave with a cross and fresh flowers in a small Franconian village cemetery', 'post'),
'lautlingen_memorial': ('COM', 0, 'memorial Stauffenberg en Lautlingen', C + ' → Category:Schloss Lautlingen',
  'Quiet museum room in a manor house with old photographs on white walls and a display case, soft daylight', 'post'),
'luneburg': ('COM', 0, 'Lüneburg (ciudad) o el brezal de Lüneburg', C + ' → Category:Lüneburg Heath',
  'Wide shot of the Lüneburg heath, purple heather and dark pine woods under gray clouds', 'post'),
'luneburg_forest': ('STK', 1, 'buscar: "dark pine forest fog" / "forest floor"', STKV,
  'Dark pine forest floor covered in needles, no grave marker, mist between the trunks', 'post'),
'braunschweig_court': ('COM', 0, 'Palacio de Justicia de Braunschweig', C + ' → Category:Landgericht Braunschweig',
  'Exterior of a stately stone courthouse in Braunschweig, 1950s', 'post'),
'stauffenberg_street': ('COM', 0, 'placas de calles "Stauffenbergstraße"', C + ' → Category:Stauffenbergstraße',
  'Street corner in a German city with an old building and a street sign pole, daylight', 'post'),
'stamp': ('COM', 0, 'sellos postales alemanes del 20 de julio / Stauffenberg (obras oficiales, dominio público)', C + ' → Category:Claus von Stauffenberg on stamps',
  'Close-up of a vintage German postage stamp with a portrait engraving of an officer, on an old envelope', 'post'),
'geloebnis': ('COM', 0, 'juramento de reclutas en el Bendlerblock el 20 de julio', C + ' → Category:Feierliches Gelöbnis',
  'Rows of young German soldiers in modern dress uniform standing at attention in a stone courtyard in Berlin, evening', 'post'),
'european_parliament': ('COM', 0, 'Parlamento Europeo (Estrasburgo) o fotos del PE con licencia CC BY', C + ' → Category:European Parliament',
  'Hemicycle of the European Parliament in Strasbourg, rows of blue seats, 1980s', 'post'),
'bundestag_bonn': ('BA', 0, 'Bundesarchiv (B 145): pleno del Bundestag en Bonn, años 70', BAW,
  'Archival style photo of the West German parliament plenary hall in Bonn in the 1970s, deputies seated in rows', 'post'),
'bundeswehr_1956': ('BA', 0, 'Bundesarchiv: primeros soldados de la Bundeswehr (1956)', BAW,
  'Archival style photo of young West German soldiers in new 1956 uniforms and helmets standing in formation', 'post'),
'bundeswehr_tanks': ('BA', 0, 'Bundesarchiv: tanques Leopard de la Bundeswehr (años 70)', BAW,
  'Archival style photo of West German Leopard tanks driving across a field in the 1970s', 'post'),
'bonn_1950s': ('BA', 0, 'Bundesarchiv: Bonn y la nueva Alemania occidental (años 50)', BAW,
  'Archival style photo of a West German city street in the early 1950s, rebuilt houses, Volkswagen Beetles', 'post'),
'veterans_1950s': ('BA', 0, 'Bundesarchiv: reunión de veteranos de la Wehrmacht (años 50)', BAW,
  'Archival style photo of a meeting of older German war veterans in civilian suits in a beer hall in the 1950s', 'post'),
'srp_rally': ('BA', 0, 'Bundesarchiv: mitin del Partido Socialista del Reich (SRP), 1951', BAW,
  'Archival style photo of a 1951 political rally in a German hall, a speaker at a podium, a crowd of men in hats', 'post'),
'oath_1934': ('BA', 0, 'Bundesarchiv: soldados prestando juramento (años 30)', BAW,
  'Archival style photo of rows of German soldiers raising their hands to take an oath, 1930s, no flags or insignia visible', 'past'),
# ---------- GUERRA (EE. UU. dominio público / Bundesarchiv) ----------
'poland_1939': ('NARA', 1, 'noticieros y fotos de la invasión de Polonia, septiembre de 1939', NARA + ' → "invasion of Poland 1939 newsreel"',
  'Archival style photo of German army columns and horse-drawn wagons on a dusty Polish road, September 1939', 'past'),
'poland_civilians': ('BA', 0, 'Bundesarchiv: civiles en Polonia, 1939 (encuadre respetuoso)', BAW,
  'Archival style photo of a market street in a small Polish town in 1939, civilians watching soldiers pass', 'past'),
'france_1940': ('BA', 0, 'Bundesarchiv: campaña de Francia, 1940', BAW,
  'Archival style photo of German army vehicles driving through a French village in May 1940', 'past'),
'officers_1930s': ('BA', 0, 'Bundesarchiv: desfile militar del rearme (1935-1936)', BAW,
  'Archival style photo of rows of marching German soldiers on a Berlin avenue in the mid-1930s, no flags or insignia visible', 'past'),
'versailles': ('COM', 0, 'firma del Tratado de Versalles (pintura o foto de dominio público)', C + ' → Category:Treaty of Versailles',
  'Painting style scene of the signing of the Treaty of Versailles in the Hall of Mirrors, 1919', 'past'),
'eastern_front': ('BA', 0, 'Bundesarchiv: frente oriental, 1941 (columnas, sin atrocidades)', BAW,
  'Archival style photo of an endless column of German soldiers marching on a muddy road across the Russian steppe in 1941', 'past'),
'soviet_pows': ('BA', 0, 'Bundesarchiv: columnas de prisioneros soviéticos, 1941', BAW,
  'Archival style photo of a huge column of exhausted Soviet prisoners of war walking across an open field in 1941', 'past'),
'okh_staff': ('BA', 0, 'Bundesarchiv: oficiales de Estado Mayor ante mapas', BAW,
  'German staff officers in plain uniforms bending over a large map table in a wooden barracks, 1942', 'past'),
'tunisia_1943': ('NARA', 1, 'campaña de Túnez 1943 (película "Tunisian Victory" y fotos del Signal Corps)', NARA + ' → "Tunisia 1943"',
  'Desert road in Tunisia in 1943, burned-out vehicles and dust clouds, tanks on the horizon', 'past'),
'p40': ('NARA', 1, 'cazas P-40 Warhawk en Túnez, 1943 (fotos de la USAAF)', NARA + ' → "P-40 Tunisia 1943"',
  'Two American P-40 Warhawk fighter planes flying low over the Tunisian desert in April 1943', 'past'),
'field_hospital': ('NARA', 0, 'hospital de campaña en Túnez, 1943', NARA + ' → "field hospital Tunisia 1943"',
  'Archival style photo of a 1943 field hospital tent in the North African desert, stretchers and medics', 'past'),
'he111': ('BA', 0, 'Bundesarchiv: avión Heinkel He 111 en vuelo', BAW + ' / Category:Heinkel He 111',
  'A German twin-engine Heinkel He 111 aircraft flying over clouds, July 1944', 'past'),
'greece_1944': ('BA', 0, 'Bundesarchiv: soldados alemanes en Grecia, 1944', BAW,
  'Archival style photo of German soldiers in a sunlit Greek town square in 1944', 'past'),
'feldgendarmerie': ('BA', 0, 'Bundesarchiv: policía militar (Feldgendarmerie)', BAW,
  'Archival style photo of German military policemen with metal gorgets checking a soldier\'s papers, 1944', 'past'),
'ju88': ('BA', 0, 'Bundesarchiv: Junkers Ju 88 / Ju 87 (aviones que probó Melitta)', BAW + ' / Category:Junkers Ju 88',
  'A German Junkers Ju 88 bomber in a steep dive over clouds, 1943', 'past'),
'iron_cross': ('COM', 0, 'la condecoración Cruz de Hierro de segunda clase (foto del objeto)', C + ' → Category:Iron Cross',
  'Close-up of a black and silver Iron Cross medal with a red, white and black ribbon on a dark velvet cloth', 'past'),
'test_airfield': ('BA', 0, 'Bundesarchiv: centro de pruebas de Rechlin / aeródromo de pruebas', BAW,
  'A German military test airfield in 1943, aircraft lined up on the grass, a hangar', 'past'),
'bucker': ('COM', 0, 'avioneta Bücker Bü 181 Bestmann', C + ' → Category:Bücker Bü 181',
  'A small single-engine Bücker Bü 181 training aircraft flying low over Bavarian fields, April 1945', 'end'),
'p51': ('NARA', 0, 'cazas P-51 Mustang (fotos de la USAAF)', NARA + ' → "P-51 Mustang 1945"',
  'An American P-51 Mustang fighter flying fast over the Bavarian countryside in April 1945', 'end'),
'refugees_1945': ('NARA', 1, 'refugiados alemanes en las carreteras, 1945 (Signal Corps)', NARA + ' → "German refugees 1945"',
  'Archival style photo of German refugees with handcarts walking along a country road in spring 1945', 'end'),
'us_troops_bavaria': ('NARA', 1, 'tropas de EE. UU. entrando en pueblos de Baviera, abril de 1945', NARA + ' → "US troops Bavaria April 1945"',
  'Archival style photo of American soldiers and jeeps entering a small Bavarian village, white flags hanging from windows, April 1945', 'end'),
'us_troops_harz': ('NARA', 1, 'tropas de EE. UU. en el Harz, abril de 1945', NARA + ' → "Harz April 1945"',
  'Archival style photo of an American army column of jeeps and trucks driving through a forested Harz valley, April 1945', 'end'),
'innsbruck_1945': ('NARA', 0, 'Innsbruck en 1945 (fotos del ejército de EE. UU.)', NARA + ' → "Innsbruck 1945"',
  'Archival style photo of Innsbruck with the snowy Alps behind it, May 1945', 'end'),
'ruins_1945': ('NARA', 1, 'ciudades alemanas en ruinas, 1945 (clips del Signal Corps)', NARA + ' → "German city ruins 1945"',
  'Archival style aerial view of a German city in ruins in 1945, roofless buildings, rubble-filled streets', 'end'),
'nuremberg_dock': ('NARA', 0, 'banquillo de los acusados en Núremberg (fotos del ejército de EE. UU.)', NARA + ' / ' + C + ' → Category:Nuremberg trials',
  'Archival style photo of the Nuremberg trial courtroom in 1946, two rows of defendants in the dock behind white-helmeted military police', 'post'),
'opel_blitz': ('BA', 0, 'Bundesarchiv: camión Opel Blitz', BAW + ' / Category:Opel Blitz',
  'A German Opel Blitz army truck with a canvas cover parked on a village road, 1945', 'end'),
'bus_1940s': ('BA', 0, 'Bundesarchiv: autobuses de los años 40', BAW,
  'A 1940s German passenger bus parked on a mountain road, 1945', 'end'),
'station_goodbye': ('BA', 0, 'Bundesarchiv: despedida de soldados en la estación (1939)', BAW,
  'Archival style photo of a soldier leaning out of a train window to say goodbye to his wife and children on a station platform, 1939', 'past'),
'jungvolk': ('BA', 0, 'Bundesarchiv: niños del Jungvolk (años 30)', BAW,
  'Archival style photo of a line of ten-year-old German boys in 1930s youth uniforms without insignia marching in a park', 'past'),
'mother_cross': ('BA', 0, 'Bundesarchiv: propaganda del "ideal de mujer" (madres, Mutterkreuz)', BAW,
  'Archival style photo of a 1930s German mother in an apron surrounded by many small children in a kitchen, posed propaganda style', 'past'),
# ---------- GLABS (personajes privados y recreaciones) ----------
'nina_young': ('GLABS', 0, 'Nina joven (no hay foto libre)', GL,
  'Dramatic close-up portrait of NINA, soft window light, thoughtful intelligent gaze, 1933', 'past'),
'nina_books': ('GLABS', 0, 'Nina entre libros y música', GL,
  'Medium shot of NINA reading a book in a 1930s Bamberg drawing room full of bookshelves, a grand piano and sheet music behind her', 'past'),
'nina_mirror': ('GLABS', 0, 'Nina frente a un espejo', GL,
  'Medium shot of NINA looking at her reflection in an old gilded mirror, her face half in shadow, 1944', 'past'),
'laundry': ('STK', 1, 'buscar: "vintage clothesline" / "white sheets clothesline wind"', STKV,
  'White cloth diapers and sheets drying on a clothesline in a farmhouse garden, 1944', 'past'),
'lerchenfeld_family': ('GLABS', 0, 'retrato familiar de los Lerchenfeld hacia 1915', GL,
  'Faded 1915 studio photograph of an aristocratic Bavarian diplomat with a mustache, his Baltic noble wife in a high-collared dress, and a small dark-haired girl in white', 'past'),
'wedding_1933': ('GLABS', 0, 'boda de Claus y Nina, Bamberg 1933', GL,
  'Wide shot of CLAUS in dress uniform and NINA in a simple white 1933 wedding dress walking out of a baroque church in Bamberg, guests throwing rice, September 1933', 'past'),
'pram': ('STK', 1, 'buscar: "vintage baby carriage" / "old pram"', STKV,
  'An old 1930s black baby carriage in a sunny garden of a Bavarian house', 'past'),
'wooden_toys': ('STK', 1, 'buscar: "vintage wooden toys" / "old toy soldiers"', STKV,
  'Old wooden toys, a rocking horse and tin soldiers on the floor of a 1930s nursery', 'past'),
'claus_baby': ('GLABS', 0, 'Claus con su hija recién nacida', GL,
  'Medium shot of CLAUS (1940) holding a newborn baby girl wrapped in a white blanket by a window, a small birthday cake with candles on the table, November 1940', 'past'),
'empty_chair': ('STK', 1, 'buscar: "empty chair window" / "empty chair old room"', STKV,
  'An empty wooden chair at the head of a family dining table by a window, afternoon light', 'past'),
'old_letters': ('STK', 1, 'buscar: "old letters" / "vintage letters envelopes"', STKV,
  'A bundle of old handwritten letters tied with string on a wooden desk', 'past'),
'letter_writing': ('STK', 1, 'buscar: "fountain pen writing letter"', STKV,
  'Close-up of a fountain pen writing a letter by lamplight in a field tent, illegible handwriting, 1939', 'past'),
'books_library': ('STK', 1, 'buscar: "old library books" / "history books"', STKV,
  'Rows of old history books on dusty library shelves, slow camera move', 'post'),
'photo_album': ('STK', 1, 'buscar: "old photo album" / "vintage family photos"', STKV,
  'Hands slowly turning the pages of an old black-and-white family photo album', 'post'),
'glove': ('STK', 1, 'buscar: "black leather glove table"', STKV,
  'A single black leather glove lying on an officer\'s desk beside a cap, 1944', 'past'),
'claus_desk': ('GLABS', 0, 'Claus leyendo informes (1942)', GL,
  'Medium shot of CLAUS (1942) reading reports alone at a desk under a green lamp late at night, troubled expression', 'past'),
'claus_desert': ('GLABS', 0, 'el ataque del 7 de abril de 1943 (sin sangre)', GL,
  'Wide shot of a burning German staff car on a desert road in Tunisia, black smoke, a wounded officer lying in the sand beside it seen from a distance, April 1943', 'past'),
'claus_patch_glabs': ('GLABS', 0, 'Claus herido, retrato', GL,
  'Dramatic close-up portrait of CLAUS (1943-1944), soft hospital window light, stoic expression', 'past'),
'shirt_buttons': ('GLABS', 0, 'detalle: un hombre con una sola mano intentando abrocharse', GL,
  'Extreme close-up of a man\'s left hand missing two fingers struggling to fasten the buttons of a white shirt, the right sleeve empty, hospital room', 'past'),
'hospital_bed': ('GLABS', 0, 'Claus en el hospital y Nina a su lado', GL,
  'Medium shot of CLAUS (1943-1944) lying in a 1943 hospital bed in Munich with bandaged arm and an eye patch, NINA sitting beside him holding his left hand', 'past'),
'nina_older_son': ('GLABS', 0, 'Nina en la posguerra hablando con su hijo', GL,
  'Medium shot of NINA (1950s) sitting at a kitchen table talking quietly with a teenage son in a 1950s sweater, cups of coffee', 'post'),
'nina_window_night': ('GLABS', 0, 'Nina sola de noche', GL,
  'Medium shot of NINA standing alone at a dark window at night, lamp light behind her, 1944', 'night'),
'briefcase': ('STK', 1, 'buscar: "vintage leather briefcase"', STKV,
  'An old brown leather briefcase standing on a wooden floor under a table, 1944', 'past'),
'couple_lamp': ('GLABS', 0, 'Claus y Nina hablando en voz baja', GL,
  'Medium shot of CLAUS (1943-1944) and NINA sitting close together by a single lamp at night, talking in whispers', 'night'),
'nina_kids_garden': ('GLABS', 0, 'Nina con los cuatro niños en Lautlingen, verano 1944', GL,
  'Wide shot of NINA in a light summer dress sitting on the lawn of a manor garden in Lautlingen with BERTHOLD, HEIMERAN, FRANZ LUDWIG and VALERIE playing around her, July 1944', 'past'),
'lautlingen_night': ('GLABS', 0, 'la puerta de Lautlingen de noche', GL,
  'The front door of a quiet manor house at night, headlights of a black car sweeping across the wall', 'night'),
'briefing_table': ('GLABS', 0, 'recreación: el maletín bajo la mesa de roble', GL,
  'Low angle close-up under a heavy oak map table in a wooden briefing hut, a brown leather briefcase on the floor among officers\' polished boots, July 1944', 'past'),
'clock': ('STK', 1, 'buscar: "vintage clock ticking"', STKV,
  'Close-up of an old wall clock, the minute hand moving to twelve forty-two', 'past'),
'teletype': ('STK', 1, 'buscar: "vintage teletype" / "old telephone switchboard"', STKV,
  'Close-up of an old 1940s telephone switchboard with cables being plugged in by a hand, red lamps blinking', 'night'),
'bendler_night': ('GLABS', 0, 'recreación: el patio del Bendlerblock de noche (sin violencia explícita)', GL,
  'Night wide shot of a stone courtyard in Berlin lit by the headlights of an army truck, a firing squad in silhouette, a pile of sand against the wall, long shadows, July 1944', 'night'),
'medals': ('STK', 1, 'buscar: "vintage military medals"', STKV,
  'Old military medals and ribbons lying on a dark field-gray uniform jacket', 'night'),
'flower_ground': ('STK', 1, 'buscar: "single flower on ground"', STKV,
  'A single white flower lying on bare earth in the rain', 'night'),
'nina_kids_sofa': ('GLABS', 0, 'Nina reúne a los niños el 21 de julio', GL,
  'Medium shot of NINA sitting on a sofa in a manor living room in the morning, holding the hands of BERTHOLD and HEIMERAN, FRANZ LUDWIG and VALERIE beside her, serious faces, 21 July 1944', 'past'),
'kids_listening': ('GLABS', 0, 'los cuatro niños escuchan a su madre', GL,
  'Close-up of the faces of BERTHOLD, HEIMERAN, FRANZ LUDWIG and VALERIE sitting close together on a sofa, listening in shocked silence, morning light, 21 July 1944', 'past'),
'old_hospital_ward': ('STK', 1, 'buscar: "old hospital ward" / "vintage hospital beds"', STKV,
  'An old hospital ward with iron beds and white sheets, light from tall windows', 'past'),
'old_family_portrait': ('STK', 0, 'buscar: "vintage family portrait" / "old family photograph"', STKF,
  'A faded early 1900s family photograph in an old frame on a lace tablecloth', 'past'),
'bamberg_church': ('COM', 0, 'iglesias barrocas y románicas de Bamberg (por ejemplo St. Jakob o la catedral)', C + ' → Category:Churches in Bamberg',
  'Exterior of an old church in Bamberg with stone steps and a wooden door, autumn light', 'past'),
'lamp_night': ('STK', 1, 'buscar: "old lamp window night"', STKV,
  'An old table lamp glowing by a dark window at night, curtains moving slightly', 'night'),
'headlights_house': ('STK', 1, 'buscar: "car headlights night house"', STKV,
  'Car headlights sweeping across the front of an old house at night', 'night'),
'phone_hand': ('STK', 1, 'buscar: "vintage telephone receiver hand"', STKV,
  'A hand picking up the receiver of an old black telephone in a dim office', 'prison'),
'hospital_corridor': ('STK', 1, 'buscar: "old hospital corridor" / "empty hospital hallway"', STKV,
  'A long empty old hospital corridor with tiled walls and a single figure in silhouette at the far end', 'prison'),
'walking_away': ('STK', 1, 'buscar: "man walking away country road"', STKV,
  'A man seen from behind walking away alone down an empty country road between fields', 'end'),
'empty_room': ('STK', 1, 'buscar: "empty abandoned room" / "empty old house interior"', STKV,
  'Interior of an empty old house, pale marks on the walls where paintings hung, dust in the light', 'post'),
'woman_path': ('STK', 1, 'buscar: "woman walking path from behind countryside"', STKV,
  'A woman seen from behind walking up a country path toward a white house, summer', 'post'),
'forest_road': ('STK', 1, 'buscar: "forest road driving" / "road through pine forest"', STKV,
  'A gravel road through a dark pine forest, seen from a moving vehicle', 'end'),
'nsv_kinderheim': ('BA', 0, 'Bundesarchiv: hogares infantiles de los años 40 (NSV-Kinderheim), niños en grupo', BAW,
  'Archival style photo of a group of German children in 1940s clothes standing in rows in front of a wooden children\'s home, a female supervisor beside them', 'prison'),
'bendler_night2': ('GLABS', 0, 'recreación: el patio del Bendlerblock visto desde arriba (sin violencia explícita)', GL,
  'High angle night shot over a stone courtyard in Berlin, four officers in field-gray uniforms being led toward a pile of sand by soldiers, lit only by the headlights of two army trucks, long shadows on the cobblestones, July 1944', 'night'),
'alps_convoy2': ('GLABS', 0, 'recreación: rostros de los rehenes por la ventanilla del autobús', GL,
  'Close shot through the dusty window of an old 1940s bus of tired civilian prisoners, an elderly man and a woman in a headscarf looking out at snowy alpine peaks, April 1945', 'end'),
'nina_young2': ('GLABS', 0, 'Nina de perfil, en sombra', GL,
  'Close-up profile of NINA half in shadow by a window at dusk, lost in thought, 1944', 'night'),
'franz_ludwig': ('COM', 0, 'Franz Ludwig Schenk Graf von Stauffenberg (foto con licencia libre)', C + ' → Category:Franz Ludwig Schenk Graf von Stauffenberg',
  'Portrait of a German politician in his fifties with gray hair and glasses in a dark suit, 1990s', 'post'),
'melitta_portrait': ('GLABS', 0, 'retrato de Melitta (no hay foto libre)', GL,
  'Dramatic portrait of MELITTA standing beside a 1940s aircraft on an airfield, flight cap in hand, confident gaze, 1943', 'past'),
'berthold_boy': ('GLABS', 0, 'Berthold a los diez años', GL,
  'Close-up of BERTHOLD looking up with a confused frown, morning light', 'past'),
'nina_answer': ('GLABS', 0, 'Nina responde a su hijo', GL,
  'Close-up of NINA looking down at her son with sad calm eyes, morning light', 'past'),
'heimeran_cry': ('GLABS', 0, 'Heimeran llora', GL,
  'Close-up of HEIMERAN crying, wiping his eyes with his sleeve, soft light', 'past'),
'gestapo_arrest': ('GLABS', 0, 'la Gestapo se lleva a Nina de noche', GL,
  'Night shot of two men in long dark leather coats and fedora hats leading NINA in a coat to a black 1940s car outside a manor house', 'night'),
'kids_window': ('GLABS', 0, 'los niños miran desde la ventana', GL,
  'Four children in nightclothes watching from an upstairs window as the red taillights of a car disappear down a village road at night', 'night'),
'chess': ('STK', 1, 'buscar: "chess piece move dark"', STKV,
  'A hand moving a black chess piece on an old wooden board in dim light', 'prison'),
'blood_ink': ('STK', 1, 'buscar: "red ink in water"', STKV,
  'Dark red ink spreading slowly in clear water against a black background', 'prison'),
'elderly_arrest': ('GLABS', 0, 'detienen a parientes ancianos', GL,
  'Medium shot of an elderly aristocratic woman with white hair in a dark coat being escorted from a manor house by two men in leather coats, morning, 1944', 'prison'),
'old_documents': ('STK', 1, 'buscar: "old documents stamp" / "vintage paperwork"', STKV,
  'An official rubber stamp slamming down on old typed documents on a desk', 'prison'),
'melitta_cockpit': ('GLABS', 0, 'Melitta en la cabina', GL,
  'Close-up of MELITTA in the open cockpit of a small trainer aircraft, wind in her hair, looking ahead, April 1945', 'end'),
'nina_cell': ('GLABS', 0, 'Nina en una celda', GL,
  'Medium shot of NINA (pregnant) sitting alone on a narrow prison bunk in a bare cell, a single barred window, cold light', 'prison'),
'nina_interrogation': ('GLABS', 0, 'Nina interrogada por la Gestapo', GL,
  'Medium shot of NINA (pregnant) sitting on a wooden chair in a bare interrogation room facing a man in a dark suit behind a desk with a typewriter, harsh desk lamp', 'prison'),
'nina_interrogation_close': ('GLABS', 0, 'Nina finge ser una ama de casa simple', GL,
  'Close-up of NINA (pregnant) with a deliberately blank, naive expression, eyes slightly lowered, hands folded, interrogation lamp on her face', 'prison'),
'typewriter': ('STK', 1, 'buscar: "vintage typewriter typing"', STKV,
  'Close-up of an old typewriter typing a report, keys striking paper, illegible text', 'prison'),
'rain_window': ('STK', 1, 'buscar: "rain on window"', STKV,
  'Rain running down a dirty window pane, gray light', 'prison'),
'nina_cell_pregnant': ('GLABS', 0, 'Nina embarazada en aislamiento', GL,
  'Close-up of NINA (pregnant) in a gray prison dress resting her hand on her belly, sitting by a small barred window, winter light', 'prison'),
'winter_window': ('STK', 1, 'buscar: "snow falling window"', STKV,
  'Snow falling outside a small barred window at dusk, January 1945', 'prison'),
'newborn': ('STK', 1, 'buscar: "newborn baby hand" / "newborn black and white"', STKV,
  'Close-up of a newborn baby\'s tiny hand gripping a woman\'s finger, wrapped in white wool', 'prison'),
'nina_baby': ('GLABS', 0, 'Nina con Konstanze en el hospital', GL,
  'Medium shot of NINA (pale and ill) in a hospital bed holding KONSTANZE, a crucifix on the white wall, 1945', 'prison'),
'gestapo_corridor': ('GLABS', 0, 'un agente de la Gestapo vigila en el hospital', GL,
  'A man in a long dark leather coat and fedora standing at the end of a long hospital corridor, a nun walking past him, 1945', 'prison'),
'ledger': ('STK', 1, 'buscar: "old hospital register" / "vintage ledger"', STKV,
  'An old hospital admission register open on a reception desk, illegible handwriting', 'prison'),
'doctor_schrank': ('GLABS', 0, 'el doctor Schrank', GL,
  'Portrait of DR SCHRANK in a white coat in a hospital office, thoughtful, 1945', 'prison'),
'doctor_bedside': ('GLABS', 0, 'el médico tranquiliza a Nina', GL,
  'Medium shot of DR SCHRANK standing at NINA\'s hospital bed, speaking quietly to her, KONSTANZE asleep in her arms', 'prison'),
'stethoscope': ('STK', 1, 'buscar: "vintage stethoscope" / "old medical instruments"', STKV,
  'An old stethoscope and medical chart on a hospital bedside table', 'prison'),
'nun_baptism': ('GLABS', 0, 'bautismo de urgencia', GL,
  'Close-up of a Catholic nun in a white habit pouring a little water from a small bowl onto the head of KONSTANZE, candlelight', 'prison'),
'candle_chapel': ('STK', 1, 'buscar: "candle dark church"', STKV,
  'A single candle burning in a dark hospital chapel', 'prison'),
'baptism': ('GLABS', 0, 'bautismo del 12 de abril de 1945', GL,
  'Medium shot of a small hospital chapel, a priest baptizing KONSTANZE held by NINA, DR SCHRANK standing as godfather, April 1945', 'prison'),
'phone_ring': ('STK', 1, 'buscar: "vintage telephone ringing"', STKV,
  'An old black 1940s telephone ringing on a desk in a dim hospital office', 'prison'),
'gestapo_phone': ('GLABS', 0, 'el agente al teléfono', GL,
  'Close-up of a man in a dark fedora speaking into an old telephone receiver, cold expression, 1945', 'prison'),
'hospital_exit': ('GLABS', 0, 'se llevan a Nina y a la bebé', GL,
  'Wide shot of NINA in a coat carrying KONSTANZE out of a red-brick hospital, escorted by a military policeman with a rifle, April 1945', 'end'),
'nina_policeman': ('GLABS', 0, 'Nina convence al policía', GL,
  'Medium shot of NINA holding KONSTANZE talking firmly to a tired middle-aged German military policeman on a village road near Hof, spring 1945', 'end'),
'policeman_leaving': ('GLABS', 0, 'el policía se va', GL,
  'Wide shot from behind of a German military policeman walking away alone down an empty country road between fields, spring 1945', 'end'),
'nina_free': ('GLABS', 0, 'Nina libre con la bebé', GL,
  'Medium shot of NINA holding KONSTANZE in a village street as American jeeps pass by, exhausted but relieved, April 1945', 'end'),
'kids_taken': ('GLABS', 0, 'se llevan a los niños de Lautlingen', GL,
  'Wide shot of BERTHOLD, HEIMERAN, FRANZ LUDWIG and VALERIE being led by a woman in a gray welfare uniform to a black car outside a manor house, August 1944', 'prison'),
'alps_convoy': ('GLABS', 0, 'convoy de rehenes por los Alpes', GL,
  'Wide shot of a convoy of old 1940s buses and trucks winding along a mountain road in the Alps, armed guards in long coats, April 1945', 'end'),
'mountain_road': ('STK', 1, 'buscar: "mountain road Alps" / "alpine pass road"', STKV,
  'Winding alpine pass road through snowy mountains', 'end'),
'bavarian_fields': ('STK', 1, 'buscar: "Bavarian fields spring" / "farmland Bavaria"', STKV,
  'Flat green fields of Lower Bavaria in spring with a church tower in the distance', 'end'),
'plane_field': ('GLABS', 0, 'la avioneta aterrizada en el campo', GL,
  'Wide shot of a small single-engine trainer airplane that has made an emergency landing in a Bavarian field, smoke rising, April 1945', 'end'),
'hostages': ('GLABS', 0, 'el grupo de rehenes', GL,
  'Wide shot of a mixed group of about one hundred and forty civilian prisoners in worn coats and hats, men, women and a few children, standing beside buses in an alpine village square, April 1945', 'end'),
'ss_guards': ('GLABS', 0, 'guardias de las SS (sin insignias)', GL,
  'Silhouettes of armed guards in long coats and helmets watching a group of prisoners at dusk, no insignia visible', 'end'),
'wehrmacht_1945': ('BA', 0, 'Bundesarchiv: soldados de la Wehrmacht, 1945', BAW,
  'Archival style photo of German army soldiers in worn uniforms in an alpine village, 1945, no insignia visible', 'end'),
'anna_portrait': ('GLABS', 0, 'Anna von Lerchenfeld (no hay foto libre)', GL,
  'Portrait of an elderly aristocratic Baltic German woman in her sixties with white hair in a bun and a black high-collared dress, 1944', 'end'),
'barbed_wire': ('STK', 1, 'buscar: "barbed wire fence winter"', STKV,
  'Rusted barbed wire fence in snow, gray sky', 'end'),
'red_cross_matron': ('GLABS', 0, 'la condesa Üxküll llega en autobús', GL,
  'Medium shot of an elderly German countess with white hair in a bun wearing a dark Red Cross matron uniform with a white collar stepping off an old bus at a wooden children\'s home, June 1945', 'post'),
'kids_bus': ('GLABS', 0, 'los niños suben al autobús', GL,
  'Wide shot of BERTHOLD, HEIMERAN, FRANZ LUDWIG and VALERIE climbing into an old 1940s bus, summer 1945', 'post'),
'nina_arrival': ('GLABS', 0, 'Nina llega a Lautlingen', GL,
  'Wide shot of NINA carrying KONSTANZE walking up the path to a white manor house in Lautlingen, June 1945', 'post'),
'reunion': ('GLABS', 0, 'el reencuentro', GL,
  'Medium shot of NINA kneeling to embrace BERTHOLD, HEIMERAN, FRANZ LUDWIG and VALERIE at once in a manor garden, June 1945', 'post'),
'siblings_baby': ('GLABS', 0, 'los hermanos conocen a Konstanze', GL,
  'Close-up of four children leaning over a baby basket looking at their tiny sister KONSTANZE for the first time', 'post'),
'looted_room': ('GLABS', 0, 'la casa de Bamberg saqueada', GL,
  'Interior of an empty looted 1940s drawing room in Bamberg, pale marks on the walls where paintings hung, an overturned chair', 'post'),
'newspapers_1950s': ('STK', 1, 'buscar: "old newspapers stack"', STKV,
  'Stacks of old yellowed newspapers tied with string, no readable headlines', 'post'),
'microphone_1950s': ('STK', 1, 'buscar: "vintage microphone stage"', STKV,
  'An old 1950s microphone on a stand at an empty podium under a spotlight', 'post'),
'courtroom_1952': ('BA', 0, 'Bundesarchiv (B 145): sala de un tribunal alemán en los años 50', BAW,
  'Wide shot of a 1952 German courtroom with wood paneling, three judges in black robes, a prosecutor with gray wavy hair standing to speak, spectators in suits', 'post'),
'scales': ('STK', 1, 'buscar: "scales of justice"', STKV,
  'Antique brass scales of justice on a dark desk, slowly balancing', 'post'),
'antique_furniture': ('STK', 1, 'buscar: "antique furniture" / "old house objects"', STKV,
  'Old antique furniture and covered objects in a dusty storage room', 'post'),
'bamberg_house': ('COM', 0, 'casa de la familia en Bamberg (si hay foto libre) o calle del casco antiguo', C + ' → Category:Bamberg',
  'A stately old townhouse in Bamberg with green shutters on a quiet street, 1953', 'post'),
'nina_older': ('GLABS', 0, 'Nina en los años 50', GL,
  'Medium shot of NINA (1950s) sitting alone by a window in a Bamberg house, a framed photograph face down on the table', 'post'),
'nina_letters': ('GLABS', 0, 'Nina guarda las cartas', GL,
  'Close-up of NINA (1950s) placing a bundle of old letters in a wooden box', 'post'),
'nina_kids_teen': ('GLABS', 0, 'Nina con sus cinco hijos en los años 50', GL,
  'Wide shot of NINA (1950s) with five children aged eight to twenty around a family table in a Bamberg house, 1953', 'post'),
'german_flag': ('STK', 1, 'buscar: "German flag waving"', STKV,
  'The black, red and gold flag of Germany waving against a blue sky', 'post'),
'quiet_lake': ('STK', 1, 'buscar: "quiet lake morning mist"', STKV,
  'A quiet lake at dawn with mist and a single rowing boat', 'post'),
'zurich': ('STK', 1, 'buscar: "Zurich old town" / "Zurich river"', STKV,
  'Zurich old town and the Limmat river at dusk', 'post'),
'law_books': ('STK', 1, 'buscar: "law books" / "legal books shelf"', STKV,
  'Rows of law books with leather spines on a shelf', 'post'),
'munich': ('STK', 1, 'buscar: "Munich old town"', STKV,
  'Munich old town and the towers of the Frauenkirche', 'post'),
'swiss_alps': ('STK', 1, 'buscar: "Switzerland village Alps"', STKV,
  'A Swiss village with green meadows and snowy Alps behind', 'post'),
'writing_book': ('STK', 1, 'buscar: "writing manuscript desk"', STKV,
  'A woman\'s hands writing a manuscript at a desk surrounded by old family photographs', 'post'),
'nina_elderly': ('GLABS', 0, 'Nina anciana', GL,
  'Portrait of NINA (old) in her nineties with white hair and a calm dignified face, soft daylight, 2000s', 'post'),
'clapperboard': ('STK', 1, 'buscar: "film clapperboard" / "film set"', STKV,
  'A film clapperboard snapping shut on a dark film set, no text visible', 'post'),
'cinema': ('STK', 1, 'buscar: "empty cinema"', STKV,
  'An empty cinema with red seats and a projector beam', 'post'),
'books_shelf': ('STK', 1, 'buscar: "book on table" / "books shelf"', STKV,
  'A history book lying on a table next to an old photograph', 'post'),
'kids_silhouettes': ('GLABS', 0, 'siluetas de los cuatro niños', GL,
  'Silhouettes of four children of different heights standing hand in hand at a window, backlit, 1944', 'prison'),
# ---------- MAPAS Y GRÁFICOS ----------
'map_germany_1944': ('MAPA', 0, 'mapa de Alemania 1944: Lautlingen, Bamberg, Berlín, Guarida del Lobo, Bad Sachsa', MAPW, 'Stylized dark map of Germany in 1944 with glowing dots on several cities, no text', 'past'),
'map_arrests': ('MAPA', 0, 'mapa de la red de detenciones (Rottweil, Berlín, Ravensbrück, Grecia, Danzig)', MAPW, 'Stylized dark map of central Europe in 1944 with red lines connecting several points, no text', 'prison'),
'map_oder': ('MAPA', 0, 'mapa del avance soviético hacia el Óder, enero de 1945, y la ruta Fráncfort del Óder → Potsdam', MAPW, 'Stylized dark map of eastern Germany in January 1945 with a red front line advancing toward a river, no text', 'prison'),
'map_nina_route': ('MAPA', 0, 'mapa de la ruta de Nina: Potsdam → (Schönberg) → Trogen/Hof', MAPW, 'Stylized dark map of Germany with a dotted route from Potsdam south to northern Bavaria, no text', 'end'),
'map_hostages': ('MAPA', 0, 'mapa de la ruta de los rehenes: Buchenwald → Regensburg → Schönberg → Dachau → Innsbruck → Niederdorf', MAPW, 'Stylized dark map of southern Germany, Austria and northern Italy with a dotted route through the Alps, no text', 'end'),
'map_danzig': ('MAPA', 0, 'mapa: Matzkau, cerca de Danzig', MAPW, 'Stylized dark map of the Baltic coast near Danzig in 1945, no text', 'end'),
'graf_title': ('GRAF', 0, 'título: "Cinco hijos. Una viuda. Un apellido." sobre fondo oscuro', GRW, 'Dark textured background with five small candles burning in a row', 'past'),
'graf_subscribe': ('GRAF', 0, 'animación del botón de suscripción del canal', GRW, 'Dark textured background with soft film grain', 'past'),
'graf_quote': ('GRAF', 0, 'cita en pantalla: "La familia Stauffenberg será exterminada hasta el último miembro" (Himmler, 3/8/1944) sobre foto oscurecida de Himmler', GRW, 'Dark textured background with soft film grain', 'prison'),
'graf_tree': ('GRAF', 0, 'árbol genealógico animado de la familia (Claus, Nina, cinco hijos, Berthold, Alexander, Melitta, Anna)', GRW, 'Dark textured background with soft film grain', 'prison'),
'graf_conspirators': ('GRAF', 0, 'collage con fotos del Bundesarchiv de Hofacker, Goerdeler y Tresckow', GRW, 'Dark textured background with soft film grain', 'prison'),
'graf_poll': ('GRAF', 0, 'gráfico de barras animado: encuesta Allensbach 1951 (40 % a favor, 30 % en contra, 30 % sin opinión)', GRW, 'Dark textured background with soft film grain', 'post'),
'graf_question': ('GRAF', 0, 'pregunta en pantalla para comentarios', GRW, 'Dark textured background with soft film grain', 'post'),
'graf_end': ('GRAF', 0, 'pantalla final con videos recomendados', GRW, 'Dark textured background with soft film grain', 'post'),
}
